name = "Wandour Forge Smp"
author = "bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "135101c87537f226d2cd99161788b7c82218d57b61adcc7cf8ec0d9aabde595c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
