name = "Wandour Forge Smp"
author = "bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b15ac39792815f07ec5d86419f42c299a06ed98a3800d185701782051cd34c1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
