name = "Wandour Forge Smp"
author = "bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2afaaec13d1a2403c7a2027ae1b00910f5ee0b86b928932d3fc3260e1fcab4cf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
